<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produks')->insert([
            [
                'nama_produk' => 'Produk 1',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama_produk' => 'Produk 2',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/zuyya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 3',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/tya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 4',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama_produk' => 'Produk 5',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/zuyya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 6',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/tya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 7',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama_produk' => 'Produk 8',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/zuyya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 9',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/tya.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 10',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 11',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama_produk' => 'Produk 12',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 13',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 14',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 15',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_produk' => 'Produk 16',
                'harga' => 250000,
                'deskripsi' => 'Deskripsi produk',
                'stok' => 15,
                'berat' => 15,
                'image' => 'img/akira.png',
                'status' => 'aktif',
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);            
    }
}
